### PR TITLE
Accessibility chapter

### PR DESCRIPTION
**Pull request by williln**
Added accessibility directory and README, and added Accessibility to the table of contents SUMMARY. 

Suggestions welcome!

### CODE REVIEW

**Comment by kerstin** [comment]
"Wishlist" copied over from Slack, as requested:

- shift responsibility for physical handouts to organisers (and possibly sponsors, for sponsor talks): coaches shouldn't have to use own time & money for creating paper printouts; they already donate free time & not all will have same resources to pay out of their own pocket. better if they just provide organisers with electronic versions of their materials (organisers = handle all the sponsor money after all)

- for the bit about scents/perfumes, the ada initiative's scent policy could possibly linked as reference

**Comment by williln** [comment]
@kerstin Done!

**Comment by olasitarska** [comment]
Amazing! :cake:

**Comment by williln** [comment]
**happy dance** Thank you!

**Pull request merged**
