### PR TITLE
Traduzido Django Girls Organizer's Manual README 

### PR DESCRIPTION
**Pull request by vihvs**
Começando a tradução naquela organização que sugeri.

### CODE REVIEW

**Comment by olasitarska** [comment]
Hi @vihvs! pt-br translation is already going on crowdin: https://crowdin.com/project/django-girls-tutorial/pt-BR :)

**Comment by vihvs** [comment]
Sorry girls, i was intend to send this request to the brazilian fork. @olasitarska i was translating the organizer manual. Is there a crowndin for that?

**Comment by olasitarska** [comment]
Ah, ok @vihvs! Noo, there isn't a crowdin for organizer's manual, we never intended to translate it. Do you think this is useful?;)

**Comment by vihvs** [comment]
@olasitarska i think it could help to start other events in brazil. other girls are helping me, so won't be a problem.

**Comment by olasitarska** [comment]
Perfect. Could you let us know when this is finished somewhere on github? I'll make sure we can merge it to this repository and publish on gitbook too :)

**Comment by vihvs** [comment]
we started the translation here https://github.com/pyladies-brazil/organizer-manual/tree/pt-br-translation
when its finished we will send a pull request. :)
We started by creating a subfolder called pt-br with the same structure inside it. Do you think this the best option?

**Comment by olasitarska** [comment]
Yes, that's exactly how gitbook works. We will then move english version to en subfolder and gitbook will do the rest :)

**Comment by vihvs** [comment]
Great! We will be in touch :smile:

**Pull request closed without merging**
