### PR TITLE
Fix links to documents (internal links)

### PR DESCRIPTION
**Pull request by bittner**
The broken references were "`README.html`" files, hence they were not translated to "`index.html`" when the HTML documents were created (just guessing). I guess replacing them by "`README.md`" would have fixed the problem, but just omitting the document names works too, and yields nicer paths.

If you want the links fixed by "`README.md`" let me know. I can do that easily.

Thanks for the great effort of DjangoGirls!

### CODE REVIEW

**Comment by olasitarska** [comment]
We're using Gitbook for displaying the manual on [organize.djangogirls.org](http://organize.djangogirls.org) and they parse markdown files to create interface in html. This is how they syntax works.

So, basically, this is all correct. I'm gonna close this PR.

**Comment by olasitarska** [comment]
Oh, I'm wrong! They actually changed something.

**Comment by olasitarska** [comment]
Ok, so I tested this PR using downloadable Gitbook app and it looks your approcach won't work either. My investigation shows that all links should be structered like that: `../promotion/README.md`, except in the file SUMMARY.md, where they should be just `promotion/README.md`. That's the only option that worked.

Do you mind fixing that? If so, please do it and open this PR again :) Thanks!

**Comment by bittner** [comment]
PR #25 should fix this finally. (I can't reopen a PR in this repo, sorry.)

**Pull request closed without merging**
