### PR TITLE
Fix file extension in document references (internal links). Fixes issue #8, was PR #19.

### PR DESCRIPTION
**Pull request by bittner**
Changes all document references from `.html` to `.md` (i.e. the actual file name).

The document collection is now browsable on GitHub, and hopefully also compatible with Gitbook.

### CODE REVIEW

**Comment by bittner** [comment]
Anyone still interested in this PR? It fixes the issues raised in issue #8 and PR #19.

**Comment by bmispelon** [comment]
Did we confirm that this does not break the links on gitbook?

If so then I'm happy to merge.

Thanks for the reminder. :snail:

**Comment by aniav** [comment]
Let's merge that! ;)

**Comment by bmispelon** [comment]
Alright! :arrow_right: :book: :boom:

**Comment by bmispelon** [comment]
Thanks @bittner, much appreciated! :gift:

**Pull request merged**
